### ISSUE TITLE
Raw HTML in completion detail pane

### ISSUE THREAD

**Issue by nelson777** [vgcpge/eclipse.copilot#6]
### Test Steps

- Create a General project
- Create a README.txt file of following content: 
  ```
  //test is ip is reachable

  function 
  ```
- Open the file via context menu: Open With/Generic Text Editor
- Invoke completion after "function " word.

### Expected Result
Clean Javascript code is shown in both completion selection list and in detail pane.

### Actual Result
Completion detail pane contains raw HTML code in addition to the completion content

<img width="958" alt="Screenshot 2023-05-18 at 22 30 07" src="https://github.com/vgcpge/eclipse.copilot/assets/129676242/77edea93-3411-4af0-a382-a7d3386e1d22">

### Notes
Generic Text Editor is provided by TextMate Core feature (org.eclipse.tm4e.feature)

**Comment by vgcpge** [comment]
Hi. Looks like a bug. Thank you for reporting. 
What are Steps to reproduce ? Can you attach the  file? What happens when you accept the suggestion? Which editor do you use? Can you try a plain text editor for the same file?

This project is a working prototype, so I accept bug reports.
The Github returned only one suggestion in this case, so there is no way to get another. The plugin shows all received suggestions in the popup. Try typing something to get another context and potentially  a different  suggestion.

**Comment by nelson777** [comment]
>What are Steps to reproduce ? 

Well I was just testing the plugin to see if it works. As soon as I tried the first suggestion it appeared that way. 

>Can you attach the file? 

Any file will do. All suggestions are like this. 

>What happens when you accept the suggestion? 

It is inserted correctly

>Which editor do you use? 

WWD 1.0.3 (Javascript)
Maybe this is the problem ? Did you intended your plugin to be Java only ?

> Can you try a plain text editor for the same file?

?? I don't understand what you mean. How can I try an Eclipse plugin in a plain text editor ? The file opens fine in a plain text editor.

>The Github returned only one suggestion in this case, so there is no way to get another.

In that specific case yes. But I tested with other cases where it also gave only one example and Neovim gave 3. Look:

Eclipse:

![msg-662214743-12373](https://github.com/vgcpge/eclipse.copilot/assets/5481589/a973f1a3-c33a-4368-8532-3b2d6b324af8)

Neovim:

![msg-662214743-12372](https://github.com/vgcpge/eclipse.copilot/assets/5481589/7b96e116-bb16-4787-a32a-c0ad7ffb9602)

**Comment by vgcpge** [comment]
[LSP4E does not suupport completion details without HTML HEAD element](https://github.com/eclipse/lsp4e/blob/1e5244520850d07c449ca1d5007c2e05196c1cad/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/hover/FocusableBrowserInformationControl.java#L165)

I will try to add a dummy HEAD.
UPDATE:
Failed:
org.eclipse.lsp4e.operations.completion.LSCompletionProposal.getAdditionalProposalInfo(IProgressMonitor) wraps the whole completion in P (paragraph) element, which implies, that the data does not contain header,  but then FocusableBrowserInformationControl expects the header to be present.
This looks to be a bug in LSP4E.

**Comment by vgcpge** [comment]
@nelson777 
I've implemented a fix to the HTML issue you reported in our most recent release, [milestone 0.0.9](https://github.com/vgcpge/eclipse.copilot/releases/download/0.0.9/update-site.zip). I appreciate your assistance in enhancing the prototype.

Could you please download this update and confirm whether the solution is effective in resolving your problem? Your feedback on this would be greatly appreciated.

In regard to the single completion problem you mentioned, I currently don't have a clear understanding of the root cause. It appears to be related to a mapping conflict in neovim that may be causing additional symbols to be entered when using Option+] in INSERT mode on MacOS, which is subsequently leading to corruption of the original document.

I plan on looking into this matter in more detail later. However, in the meantime, it would be beneficial if you could create a separate bug report for this issue. By doing so, it allows me to better track and address each problem individually, ensuring that nothing gets overlooked.

Thank you once again for your support and cooperation.

**Comment by nelson777** [comment]
Sure... about the HTML the problem was solved. Thanks!

I will open the bug report you asked me.

![msg-662214743-12374](https://github.com/vgcpge/eclipse.copilot/assets/5481589/50387f93-458a-46ac-804d-861f3420a02a)

**Comment by nelson777** [comment]
> Thank you once again for your support and cooperation.

It's me that's very glad to help you saving we Eclipse users. I thought I would have to abandon Eclipse development this time. And I really like Eclipse, didn't want to do that. :)
